### ISSUE TITLE
dschz's recommendations for Athens, GR

### ISSUE THREAD

**Issue by dschz** [githubteacher/developers-july-AM#15]
# Athens, Greece

- [ ] Create a branch

- [ ] Add a file

- [ ] Commit my changes

- [ ] Open a pull request

- [ ] Collaborate with my friends

- [ ] Get a 👍 

- [ ] Merge the pull request to master

**Comment by UTCWebDev** [comment]
Sorry I missed all that work, thanks for completing the assignment! 👍
