### ISSUE TITLE
add me to collaborator

### ISSUE THREAD

**Issue by tejeskave** [githubteacher/developers-july-AM#3]

**Comment by paulmcwilliams** [comment]
Paul from Belfast

**Comment by tejeskave** [comment]
I am from veszprém

**Comment by username-is-already-taken2** [comment]
you need to add a comment to this issue https://github.com/githubteacher/developers-july-AM/issues/2

**Comment by rahulpundlik07** [comment]
I AM FROM INDIA

**Comment by paulmcwilliams** [comment]
Paul from Belfast

**Comment by githubteacher** [comment]
:tada: @paulmcwilliams, @tejeskave, @rahulpundlik07, and @paulmcwilliams are now  repository collaborators. :balloon:

**Comment by aganh** [comment]
Aditya from chicago

**Comment by riv3n** [comment]
hi
