### ISSUE TITLE
vavrtom recommendations for Prague, Czech Republic

### ISSUE THREAD

**Issue by vavrtom** [githubteacher/developers-july-AM#31]
# Prague, Czech Republic

- [ ] Create a branch
- [ ] Add a file
- [ ] Commit my changes
- [ ] Open a pull request
- [ ] Collaborate with my friends
- [ ] Get a +1
- [ ] Merge the Pull Request to master

Anything I forgot, @krasmar?

**Comment by krasmar** [comment]
Put a space character between two brackets ;)

**Comment by vavrtom** [comment]
Done. :)
