### ISSUE TITLE
GitHubTeacher's recommendations for Fuquay Varina, NC

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/developers-july-AM#7]
# Fuquay Varina, NC

- [x] Create a branch
- [x] Add a file
- [x] Commit my changes
- [x] Open a pull request
- [x] Collaborate with my new friends (YOU!)
- [ ] Get a :+1:
- [ ] Merge the Pull Request to master

Anything I forgot @halfaro1?

**Comment by halfaro1** [comment]
Looks ✨ @crichID! Can't wait to get started.
